## sckit learn 으로 학습하는 방법
### 1. 우리가 원하는 모델을 만든다
### 2. 만든 모델을 fit이라는 method로 학습을 시킨다
### 3. 학습이 완료된 모델을 predict하는 method로 검증한다

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression


In [3]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3

print(X,y)

[[1 1]
 [1 2]
 [2 2]
 [2 3]] [ 6  8  9 11]


In [4]:
mdl = LinearRegression()

mdl.fit(X, y)

LinearRegression()

In [5]:
y_pred = mdl.predict(X)
print(y_pred)

[ 6.  8.  9. 11.]


In [6]:
mdl.predict([[3,3]])

array([12.])

In [8]:
from sklearn.datasets import load_iris, load_wine

iris_data = load_iris()
wine_data = load_wine()

In [9]:
X, y = iris_data.data, iris_data.target

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [20]:
Y_pred = lr.predict(X)
print(y, '\n', np.round(Y_pred))
print(y-np.round(Y_pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 
 [-0. -0. -0.  0. -0.  0.  0. -0.  0. -0. -0.  0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0.  0. -0.  0.  0. -0.  0. -0. -0.  0.  0.  0. -0. -0. -0. -0.
 -0. -0. -0. -0. -0.  0. -0.  0.  0.  0. -0. -0. -0. -0.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  1.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0. 

In [14]:
lr.predict([[1,3,5,6]])

array([4.75308839])

In [22]:
lr.coef_

array([-0.11190585, -0.04007949,  0.22864503,  0.60925205])

In [24]:
lr.intercept_

0.18649524720624944