In [2]:
import numpy as np

In [3]:
data1 = [1,2,3,4,5]
print(data1, type(data1))

[1, 2, 3, 4, 5] <class 'list'>


In [4]:
data2 = [1,2,3,3,5,4]
data2

[1, 2, 3, 3, 5, 4]

In [5]:
arr1 = np.array(data1)
arr1
print(arr1, type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
arr1.shape

(5,)

In [7]:
arr2 = np.array(data2)
arr2.dtype
print(arr1.dtype, arr2.dtype)

int32 int32


In [8]:
arr3 = np.array(data2)
arr3

array([1, 2, 3, 3, 5, 4])

In [9]:
arr3.shape

(6,)

In [10]:
arr3.dtype

dtype('int32')

In [11]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr4.shape

(4, 3)

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(-10,10,0.1)

array([-1.00000000e+01, -9.90000000e+00, -9.80000000e+00, -9.70000000e+00,
       -9.60000000e+00, -9.50000000e+00, -9.40000000e+00, -9.30000000e+00,
       -9.20000000e+00, -9.10000000e+00, -9.00000000e+00, -8.90000000e+00,
       -8.80000000e+00, -8.70000000e+00, -8.60000000e+00, -8.50000000e+00,
       -8.40000000e+00, -8.30000000e+00, -8.20000000e+00, -8.10000000e+00,
       -8.00000000e+00, -7.90000000e+00, -7.80000000e+00, -7.70000000e+00,
       -7.60000000e+00, -7.50000000e+00, -7.40000000e+00, -7.30000000e+00,
       -7.20000000e+00, -7.10000000e+00, -7.00000000e+00, -6.90000000e+00,
       -6.80000000e+00, -6.70000000e+00, -6.60000000e+00, -6.50000000e+00,
       -6.40000000e+00, -6.30000000e+00, -6.20000000e+00, -6.10000000e+00,
       -6.00000000e+00, -5.90000000e+00, -5.80000000e+00, -5.70000000e+00,
       -5.60000000e+00, -5.50000000e+00, -5.40000000e+00, -5.30000000e+00,
       -5.20000000e+00, -5.10000000e+00, -5.00000000e+00, -4.90000000e+00,
       -4.80000000e+00, -

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1.shape

(2, 3)

In [23]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [24]:
arr2.shape

(2, 3)

In [25]:
print(type(data1), type(data2))
print(data1+data2)

<class 'list'> <class 'list'>
[1, 2, 3, 4, 5, 1, 2, 3, 3, 5, 4]


In [26]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [27]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [28]:
arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [29]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [31]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr1.shape

(2, 3)

In [34]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [35]:
arr3.shape

(3,)

In [36]:
arr1+arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [37]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [38]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [39]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [41]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1[0]

0

In [43]:
arr1[3]

3

In [50]:
arr1[3:9]


array([3, 4, 5, 6, 7, 8])

In [51]:
arr1[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
arr1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
arr2.shape

(3, 4)

In [54]:
list1 = [[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]]
list1[0][0]

1

In [47]:
arr2[0,0]

1

In [48]:
arr2[2,:]

array([ 9, 10, 11, 12])

In [56]:
arr2[2,3]

12

In [57]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [58]:
names.shape

(8,)

In [98]:
data = np.random.randn(8,4)
print(data)
print(data > 0)

[[-0.40239699 -0.39046525  1.29840961  0.49508986]
 [ 0.70562472 -0.68644228  0.3217097  -0.00311   ]
 [-0.54136171 -0.96750275  1.72662968  0.33970361]
 [ 0.99337386 -1.05321944  1.89903496  0.93344669]
 [-0.40482595  1.4827785  -0.32769709  1.33482683]
 [ 0.55211533  0.91364869  0.5252035   0.1626267 ]
 [ 1.48776457 -0.3976547  -0.51712824 -1.64865437]
 [ 0.65025599 -0.20003265  0.18395034 -0.79086771]]
[[False False  True  True]
 [ True False  True False]
 [False False  True  True]
 [ True False  True  True]
 [False  True False  True]
 [ True  True  True  True]
 [ True False False False]
 [ True False  True False]]


In [99]:
np.mean(data)

0.2398385622027138

In [100]:
data.shape

(8, 4)

In [101]:
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [102]:
data[names_Beomwoo_mask,:]

array([[-0.40239699, -0.39046525,  1.29840961,  0.49508986],
       [ 0.70562472, -0.68644228,  0.3217097 , -0.00311   ],
       [ 0.55211533,  0.91364869,  0.5252035 ,  0.1626267 ],
       [ 0.65025599, -0.20003265,  0.18395034, -0.79086771]])

In [103]:
data[names == 'Kim',:]

array([[-0.54136171, -0.96750275,  1.72662968,  0.33970361]])

In [104]:
data[(names == 'Kim') | (names == 'Park'), :]

array([[-0.54136171, -0.96750275,  1.72662968,  0.33970361],
       [ 1.48776457, -0.3976547 , -0.51712824, -1.64865437]])

In [105]:
data[:,0] < 0

array([ True, False,  True, False,  True, False, False, False])

In [106]:
data[data[:,0]<0, :]

array([[-0.40239699, -0.39046525,  1.29840961,  0.49508986],
       [-0.54136171, -0.96750275,  1.72662968,  0.33970361],
       [-0.40482595,  1.4827785 , -0.32769709,  1.33482683]])

In [107]:
data[data[:,0]<0, 2:4]

array([[ 1.29840961,  0.49508986],
       [ 1.72662968,  0.33970361],
       [-0.32769709,  1.33482683]])

In [108]:
data[data[:,0]<0, 2:4] = 0
data

array([[-0.40239699, -0.39046525,  0.        ,  0.        ],
       [ 0.70562472, -0.68644228,  0.3217097 , -0.00311   ],
       [-0.54136171, -0.96750275,  0.        ,  0.        ],
       [ 0.99337386, -1.05321944,  1.89903496,  0.93344669],
       [-0.40482595,  1.4827785 ,  0.        ,  0.        ],
       [ 0.55211533,  0.91364869,  0.5252035 ,  0.1626267 ],
       [ 1.48776457, -0.3976547 , -0.51712824, -1.64865437],
       [ 0.65025599, -0.20003265,  0.18395034, -0.79086771]])

In [126]:
arr1 = np.random.randn(5,3)
arr1


array([[-0.34169145, -0.1831577 ,  0.80657415],
       [ 1.58184212, -0.46076554, -0.43734569],
       [ 0.33138025, -1.82841724,  1.68478528],
       [ 0.4821453 , -0.04165643,  0.416382  ],
       [ 1.24031419, -1.38861513,  2.19392674]])

In [127]:
arr2 = np.random.normal(0,1,(5,3))
arr2

array([[ 2.27227722e+00,  2.55463237e-01, -2.79921690e-02],
       [-6.98039093e-01,  6.89325991e-01,  2.34782125e-01],
       [ 1.73019054e+00,  6.50280181e-04,  7.67552118e-02],
       [ 3.50353903e+00,  1.99734887e-02,  7.43487607e-01],
       [-6.88320696e-01,  1.26308944e+00, -1.23165160e+00]])

In [128]:
np.abs(arr1)

array([[0.34169145, 0.1831577 , 0.80657415],
       [1.58184212, 0.46076554, 0.43734569],
       [0.33138025, 1.82841724, 1.68478528],
       [0.4821453 , 0.04165643, 0.416382  ],
       [1.24031419, 1.38861513, 2.19392674]])

In [129]:
np.sqrt(arr1)

<ipython-input-129-31bdbbe4b4c3>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[       nan,        nan, 0.89809473],
       [1.25771305,        nan,        nan],
       [0.57565636,        nan, 1.29799279],
       [0.69436684,        nan, 0.64527668],
       [1.11369394,        nan, 1.48119099]])

In [130]:
np.square(arr1)

array([[1.16753045e-01, 3.35467419e-02, 6.50561853e-01],
       [2.50222450e+00, 2.12304885e-01, 1.91271253e-01],
       [1.09812869e-01, 3.34310961e+00, 2.83850145e+00],
       [2.32464093e-01, 1.73525784e-03, 1.73373968e-01],
       [1.53837929e+00, 1.92825197e+00, 4.81331452e+00]])

In [134]:
print(np.square(arr1),'\n', arr1**2)

[[1.16753045e-01 3.35467419e-02 6.50561853e-01]
 [2.50222450e+00 2.12304885e-01 1.91271253e-01]
 [1.09812869e-01 3.34310961e+00 2.83850145e+00]
 [2.32464093e-01 1.73525784e-03 1.73373968e-01]
 [1.53837929e+00 1.92825197e+00 4.81331452e+00]] 
 [[1.16753045e-01 3.35467419e-02 6.50561853e-01]
 [2.50222450e+00 2.12304885e-01 1.91271253e-01]
 [1.09812869e-01 3.34310961e+00 2.83850145e+00]
 [2.32464093e-01 1.73525784e-03 1.73373968e-01]
 [1.53837929e+00 1.92825197e+00 4.81331452e+00]]


In [135]:
print(np.square(arr1) - arr1**2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [136]:
np.exp(arr1)

array([[0.71056742, 0.83263684, 2.24022016],
       [4.86390748, 0.63080056, 0.64574816],
       [1.39288934, 0.16066766, 5.39129321],
       [1.61954509, 0.95919928, 1.51646504],
       [3.45669935, 0.24942048, 8.97036831]])

In [137]:
np.log(arr1)

<ipython-input-137-ee4fb0b16e6c>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[        nan,         nan, -0.21495945],
       [ 0.45859007,         nan,         nan],
       [-1.10448878,         nan,  0.52163813],
       [-0.72950975,         nan, -0.87615218],
       [ 0.21536473,         nan,  0.78569297]])

In [138]:
np.log10(arr1)

<ipython-input-138-53e7f8b3389a>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)


array([[        nan,         nan, -0.0933557 ],
       [ 0.19916314,         nan,         nan],
       [-0.47967338,         nan,  0.22654456],
       [-0.31682206,         nan, -0.38050806],
       [ 0.09353171,         nan,  0.34122212]])

In [139]:
np.log2(arr1)

<ipython-input-139-b8a38c33f7f8>:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[        nan,         nan, -0.31012093],
       [ 0.66160562,         nan,         nan],
       [-1.59344048,         nan,  0.75256474],
       [-1.0524601 ,         nan, -1.2640204 ],
       [ 0.31070562,         nan,  1.13351535]])

In [140]:
np.sign(arr1)

array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.]])

In [141]:
np.ceil(arr1)

array([[-0., -0.,  1.],
       [ 2., -0., -0.],
       [ 1., -1.,  2.],
       [ 1., -0.,  1.],
       [ 2., -1.,  3.]])

In [142]:
np.floor(arr1)

array([[-1., -1.,  0.],
       [ 1., -1., -1.],
       [ 0., -2.,  1.],
       [ 0., -1.,  0.],
       [ 1., -2.,  2.]])

In [143]:
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [148]:
np.isnan(np.log2(arr1))

<ipython-input-148-7cec7a4af6d5>:1: RuntimeWarning: invalid value encountered in log2
  np.isnan(np.log2(arr1))


array([[ True,  True, False],
       [False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [149]:
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [150]:
np.cos(arr1)

array([[ 0.94218924,  0.98327347,  0.69197568],
       [-0.01104557,  0.89571237,  0.90587905],
       [ 0.94559418, -0.2547807 , -0.11374227],
       [ 0.88600223,  0.9991325 ,  0.91455824],
       [ 0.32449911,  0.18117511, -0.58358008]])

In [151]:
np.tanh(arr1)

array([[-0.32898661, -0.1811367 ,  0.66769605],
       [ 0.91888909, -0.43070794, -0.41144188],
       [ 0.31976045, -0.949671  ,  0.93347977],
       [ 0.44796007, -0.04163235,  0.39387809],
       [ 0.84554518, -0.88286583,  0.97545034]])

In [152]:
arr1

array([[-0.34169145, -0.1831577 ,  0.80657415],
       [ 1.58184212, -0.46076554, -0.43734569],
       [ 0.33138025, -1.82841724,  1.68478528],
       [ 0.4821453 , -0.04165643,  0.416382  ],
       [ 1.24031419, -1.38861513,  2.19392674]])

In [153]:
arr2 = np.random.randn(5,3)
arr2

array([[ 0.56537877,  0.19136196,  1.03394122],
       [ 1.97483584,  0.01357671,  0.6466707 ],
       [-1.32748036, -0.5940651 ,  1.50202149],
       [-0.75031724, -0.284981  ,  0.32320583],
       [ 0.54612262,  1.70716702,  1.26861421]])

In [154]:
np.multiply(arr1,arr2)

array([[-0.19318509, -0.03504942,  0.83395025],
       [ 3.12387851, -0.00625568, -0.28281864],
       [-0.43990077,  1.08619887,  2.53058371],
       [-0.36176193,  0.01187129,  0.13457709],
       [ 0.67736364, -2.37059795,  2.78324662]])

In [157]:
np.add(arr1,arr2)

array([[ 0.22368732,  0.00820426,  1.84051536],
       [ 3.55667796, -0.44718884,  0.20932501],
       [-0.99610011, -2.42248234,  3.18680678],
       [-0.26817193, -0.32663743,  0.73958783],
       [ 1.78643681,  0.3185519 ,  3.46254094]])

In [158]:
np.subtract(arr1,arr2)

array([[-0.90707022, -0.37451966, -0.22736707],
       [-0.39299371, -0.47434225, -1.08401639],
       [ 1.6588606 , -1.23435214,  0.18276379],
       [ 1.23246254,  0.24332458,  0.09317616],
       [ 0.69419157, -3.09578215,  0.92531253]])

In [165]:
np.divide(arr1, arr2)

array([[ -0.60435847,  -0.957127  ,   0.78009671],
       [  0.8009993 , -33.9379473 ,  -0.67630355],
       [ -0.249631  ,   3.07780619,   1.12167855],
       [ -0.6425886 ,   0.14617264,   1.28828738],
       [  2.27112765,  -0.8134032 ,   1.72938844]])

In [155]:
np.maximum(arr1,arr2)

array([[ 0.56537877,  0.19136196,  1.03394122],
       [ 1.97483584,  0.01357671,  0.6466707 ],
       [ 0.33138025, -0.5940651 ,  1.68478528],
       [ 0.4821453 , -0.04165643,  0.416382  ],
       [ 1.24031419,  1.70716702,  2.19392674]])

In [159]:
arr1

array([[-0.34169145, -0.1831577 ,  0.80657415],
       [ 1.58184212, -0.46076554, -0.43734569],
       [ 0.33138025, -1.82841724,  1.68478528],
       [ 0.4821453 , -0.04165643,  0.416382  ],
       [ 1.24031419, -1.38861513,  2.19392674]])

In [160]:
np.sum(arr1)

4.055700855489928

In [166]:
np.sum(arr1, axis = 0)

array([ 3.29399042, -3.90261203,  4.66432247])

In [167]:
np.mean(arr1)

0.2703800570326618

In [175]:
np.mean(arr1, axis= 1)

array([0.09390833, 0.2279103 , 0.06258276, 0.28562362, 0.68187527])

In [176]:
np.std(arr1)

1.0828673257984482

In [177]:
np.min(arr1, axis = 1)

array([-0.34169145, -0.46076554, -1.82841724, -0.04165643, -1.38861513])

In [178]:
np.argmin(arr1)

7

In [179]:
np.argmax(arr1, axis= 0)

array([1, 3, 4], dtype=int64)

In [180]:
np.cumsum(arr1)

array([-0.34169145, -0.52484914,  0.281725  ,  1.86356712,  1.40280158,
        0.96545589,  1.29683614, -0.5315811 ,  1.15320418,  1.63534949,
        1.59369306,  2.01007506,  3.25038925,  1.86177412,  4.05570086])

In [181]:
np.cumsum(arr1, axis= 1)

array([[-0.34169145, -0.52484914,  0.281725  ],
       [ 1.58184212,  1.12107658,  0.68373089],
       [ 0.33138025, -1.49703699,  0.18774829],
       [ 0.4821453 ,  0.44048888,  0.85687087],
       [ 1.24031419, -0.14830094,  2.0456258 ]])

In [182]:
np.cumprod(arr1)

array([-3.41691447e-01,  6.25834185e-02,  5.04781673e-02,  7.98484913e-02,
       -3.67914334e-02,  1.60905748e-02,  5.33209868e-03, -9.74930117e-03,
       -1.64254791e-02, -7.91946762e-03,  3.29896718e-04,  1.37363054e-04,
        1.70373346e-04, -2.36583005e-04, -5.19045779e-04])

In [183]:
arr1

array([[-0.34169145, -0.1831577 ,  0.80657415],
       [ 1.58184212, -0.46076554, -0.43734569],
       [ 0.33138025, -1.82841724,  1.68478528],
       [ 0.4821453 , -0.04165643,  0.416382  ],
       [ 1.24031419, -1.38861513,  2.19392674]])

In [184]:
np.sort(arr1)

array([[-0.34169145, -0.1831577 ,  0.80657415],
       [-0.46076554, -0.43734569,  1.58184212],
       [-1.82841724,  0.33138025,  1.68478528],
       [-0.04165643,  0.416382  ,  0.4821453 ],
       [-1.38861513,  1.24031419,  2.19392674]])

In [185]:
np.sort(arr1)[::-1]

array([[-1.38861513,  1.24031419,  2.19392674],
       [-0.04165643,  0.416382  ,  0.4821453 ],
       [-1.82841724,  0.33138025,  1.68478528],
       [-0.46076554, -0.43734569,  1.58184212],
       [-0.34169145, -0.1831577 ,  0.80657415]])

In [186]:
np.sort(arr1, axis= 0)

array([[-0.34169145, -1.82841724, -0.43734569],
       [ 0.33138025, -1.38861513,  0.416382  ],
       [ 0.4821453 , -0.46076554,  0.80657415],
       [ 1.24031419, -0.1831577 ,  1.68478528],
       [ 1.58184212, -0.04165643,  2.19392674]])